import { ArrowDown, MoveRight } from "lucide-react";
import { Callout, Process, ProjectsGrid, SectionIntro, ServicesGrid, TrustSection, ValueList } from "@/components/sections";
import { NeuralNetworkBackground } from "@/components/hero/neural-network-background";
import { ArrowLink, Footer, Header, HeroEntrance, HeroItem, Reveal } from "@/components/site-shell";
import { site } from "@/lib/content";

export default function Home() {
  return <><Header /><main>
      <section className="hero-grid relative overflow-hidden px-5 pb-20 pt-36 sm:px-8 sm:pb-28 sm:pt-48"><NeuralNetworkBackground /><HeroEntrance className="relative z-10 mx-auto grid max-w-7xl gap-16 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><HeroItem><p className="label text-coral">AI systems · Digital products · Better work</p><h1 className="mt-6 max-w-[10.5ch] font-display text-[clamp(2.8rem,11vw,8.5rem)] leading-[.9] tracking-[-.04em] sm:max-w-5xl">Intelligence, made <span className="text-coral">useful.</span></h1></HeroItem><HeroItem className="lg:pb-3"><p className="max-w-md text-base leading-relaxed text-ink/65 sm:text-lg">{site.description} From first question to lasting advantage, we make ambitious technology feel clear.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:flex-wrap sm:items-center sm:gap-5"><a href="#services" className="button button-dark">Explore services <ArrowDown size={15} /></a><ArrowLink href="/contact">Start a project</ArrowLink></div></HeroItem></HeroEntrance><div className="relative z-10 mx-auto mt-20 flex max-w-7xl items-center gap-3 text-sm text-ink/45"><span className="scroll-cue grid h-8 w-8 place-items-center rounded-full border border-ink/20"><MoveRight size={15} /></span>Scroll to explore</div></section>
    <section className="px-5 py-24 sm:px-8 sm:py-32"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.8fr_1.2fr]"><Reveal><p className="label text-coral">The short version</p></Reveal><Reveal><p className="max-w-4xl font-display text-3xl leading-tight sm:text-5xl">The next wave of technology is not about more noise. It is about giving good people better tools to think, make, and move.</p><div className="mt-10 grid gap-8 sm:grid-cols-2"><ValueList /><p className="text-sm leading-relaxed text-ink/60">M2N Link Solutions est un partenaire technologique independant pour les organisations qui construisent leur avenir. Nous associons vision produit et expertise technique pour livrer des solutions utiles et fiables.</p></div></Reveal></div></section>
    <section id="services" className="bg-mint px-5 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow="What we make possible" title="The right capability for the real problem." copy="From intelligent web platforms and mobile apps to applied AI, our teams turn complex ideas into products people can use every day." /><ServicesGrid limit={4} /><div className="mt-10"><ArrowLink href="/services">View all capabilities</ArrowLink></div></div></section>
    <section className="px-5 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow="Selected work" title="Proof lives in the details." copy="A few ways we have helped teams turn complexity into momentum." /><ProjectsGrid /></div></section>
    <TrustSection />
    <section className="px-5 py-24 sm:px-8 sm:py-32"><div className="mx-auto max-w-7xl"><SectionIntro eyebrow="How we work" title="A clear path through uncertain territory." /><Process /></div></section>
    <Callout />
  </main><Footer /></>;
}
